package com.drshoes.app.audit.dto;
public enum TimelineEventKind {
    ORDER_CREATED,
    ORDER_UPDATED,
    STATUS_CHANGED,
    ASSIGNEE_CHANGED,
    PICKUP_DATE_CHANGED,
    ITEM_ADDED,
    ITEM_EDITED,
    ITEM_REMOVED,
    ORDER_SOFT_DELETED,
    MESSAGE_SENT,
    MESSAGE_DELIVERED,
    MESSAGE_FAILED,
    PHOTO_UPLOADED,
    PHOTO_DELETED,
    PHOTO_RELABELED,
    MESSAGE_RECEIVED,
    THREAD_MARKED_READ,
    THREAD_ASSIGNED,
    THREAD_DISCARDED,
    ORDER_NOTE,
    DONE
}
