-- V035 — Email footer v3: always-dark band (robust to Gmail/Outlook dark mode).
--
-- Bug: V031 footer was cream-bg + ink-color text. Inline color:#0a0a0a survives
-- Gmail dark-mode CSS inversion (which only repaints backgrounds, not explicit
-- foregrounds). Result: dark-on-dark workshop signature, unreadable.
-- The `@media (prefers-color-scheme: dark) .ink-text { color !important }` rule
-- is stripped by Gmail's CSS sanitizer, so the planned light-mode-only override
-- never reaches the rendered DOM.
--
-- Fix: pin the footer to its own dark color block. Same in light AND dark mode →
-- email clients can't mis-render it. Brand palette stays intact (ink #0a0a0a,
-- cream #f4efe6, acid #d8ff3a, muted cream #b8b3a5).
--
-- Idempotent: REPLACE is a no-op if the v2 string isn't present, and the
-- NOT LIKE '%background:#0a0a0a;border-top:3px solid #d8ff3a;%' guard skips
-- rows already at v3.

-- ─── 1. Zlecenie przyjete (EMAIL) ───────────────────────────────────────────────────────────
UPDATE message_template
SET body_html = REPLACE(
    body_html,
    E'  <!-- FOOTER -->\n  <tr><td class="footer-bg ink-text" style="background:#ebe4d4;border-top:2px solid #0a0a0a;padding:28px 32px 30px;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif;color:#0a0a0a;">\n    <div style="font-family:Impact,\'Arial Black\',\'Helvetica Inserat\',sans-serif;font-size:20px;line-height:22px;letter-spacing:.02em;text-transform:uppercase;color:#0a0a0a;font-weight:900;margin-bottom:14px;">{nazwa_warsztatu}</div>\n    <div style="font-size:15px;line-height:22px;color:#0a0a0a;font-weight:600;margin-bottom:6px;">{adres_warsztatu}</div>\n    <div style="font-size:15px;line-height:22px;color:#0a0a0a;margin-bottom:6px;">tel. <a href="tel:+48514296809" style="color:#0a0a0a;text-decoration:none;font-weight:700;">{telefon_warsztatu}</a></div>\n    <div style="font-size:13px;line-height:20px;color:#3a3833;margin-bottom:18px;">{godziny_otwarcia}</div>\n    <table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr><td style="background:#d8ff3a;padding:0;">\n      <a href="{mapy_url}" target="_blank" rel="noopener" style="display:inline-block;background:#d8ff3a;color:#0a0a0a;text-decoration:none;font-family:Impact,\'Arial Black\',\'Helvetica Inserat\',sans-serif;font-size:15px;line-height:15px;letter-spacing:.14em;text-transform:uppercase;padding:14px 24px;font-weight:900;">&#x2192; Mapa dojazdu</a>\n    </td></tr></table>\n    <div style="margin-top:20px;font-size:11px;line-height:16px;color:#6b6960;opacity:.85;">Odpisz STOP, jeśli nie chcesz dostawać powiadomień o swoich zleceniach.</div>\n  </td></tr>',
    E'  <!-- FOOTER v3 (always-dark; resists dark-mode CSS inversion) -->\n  <tr><td class="footer-bg" bgcolor="#0a0a0a" style="background:#0a0a0a;border-top:3px solid #d8ff3a;padding:28px 32px 30px;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif;color:#f4efe6;">\n    <div style="font-family:Impact,\'Arial Black\',\'Helvetica Inserat\',sans-serif;font-size:20px;line-height:22px;letter-spacing:.02em;text-transform:uppercase;color:#f4efe6;font-weight:900;margin-bottom:14px;">{nazwa_warsztatu}</div>\n    <div style="font-size:15px;line-height:22px;color:#f4efe6;font-weight:600;margin-bottom:6px;">{adres_warsztatu}</div>\n    <div style="font-size:15px;line-height:22px;color:#f4efe6;margin-bottom:6px;">tel. <a href="tel:+48514296809" style="color:#d8ff3a;text-decoration:none;font-weight:700;">{telefon_warsztatu}</a></div>\n    <div style="font-size:13px;line-height:20px;color:#b8b3a5;margin-bottom:18px;">{godziny_otwarcia}</div>\n    <table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr><td style="background:#d8ff3a;padding:0;">\n      <a href="{mapy_url}" target="_blank" rel="noopener" style="display:inline-block;background:#d8ff3a;color:#0a0a0a;text-decoration:none;font-family:Impact,\'Arial Black\',\'Helvetica Inserat\',sans-serif;font-size:15px;line-height:15px;letter-spacing:.14em;text-transform:uppercase;padding:14px 24px;font-weight:900;">&#x2192; Mapa dojazdu</a>\n    </td></tr></table>\n    <div style="margin-top:20px;font-size:11px;line-height:16px;color:#8a8780;opacity:.85;">Odpisz STOP, jeśli nie chcesz dostawać powiadomień o swoich zleceniach.</div>\n  </td></tr>'
)
WHERE name = 'Zlecenie przyjete (EMAIL)'
  AND body_html IS NOT NULL
  AND body_html NOT LIKE '%background:#0a0a0a;border-top:3px solid #d8ff3a;%';

-- ─── 2. Gotowe do odbioru (EMAIL) ───────────────────────────────────────────────────────────
UPDATE message_template
SET body_html = REPLACE(
    body_html,
    E'  <!-- FOOTER -->\n  <tr><td class="footer-bg ink-text" style="background:#ebe4d4;border-top:2px solid #0a0a0a;padding:28px 32px 30px;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif;color:#0a0a0a;">\n    <div style="font-family:Impact,\'Arial Black\',\'Helvetica Inserat\',sans-serif;font-size:20px;line-height:22px;letter-spacing:.02em;text-transform:uppercase;color:#0a0a0a;font-weight:900;margin-bottom:14px;">{nazwa_warsztatu}</div>\n    <div style="font-size:15px;line-height:22px;color:#0a0a0a;font-weight:600;margin-bottom:6px;">{adres_warsztatu}</div>\n    <div style="font-size:15px;line-height:22px;color:#0a0a0a;margin-bottom:6px;">tel. <a href="tel:+48514296809" style="color:#0a0a0a;text-decoration:none;font-weight:700;">{telefon_warsztatu}</a></div>\n    <div style="font-size:13px;line-height:20px;color:#3a3833;margin-bottom:18px;">{godziny_otwarcia}</div>\n    <table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr><td style="background:#d8ff3a;padding:0;">\n      <a href="{mapy_url}" target="_blank" rel="noopener" style="display:inline-block;background:#d8ff3a;color:#0a0a0a;text-decoration:none;font-family:Impact,\'Arial Black\',\'Helvetica Inserat\',sans-serif;font-size:15px;line-height:15px;letter-spacing:.14em;text-transform:uppercase;padding:14px 24px;font-weight:900;">&#x2192; Mapa dojazdu</a>\n    </td></tr></table>\n    <div style="margin-top:20px;font-size:11px;line-height:16px;color:#6b6960;opacity:.85;">Odpisz STOP, jeśli nie chcesz dostawać powiadomień o swoich zleceniach.</div>\n  </td></tr>',
    E'  <!-- FOOTER v3 (always-dark; resists dark-mode CSS inversion) -->\n  <tr><td class="footer-bg" bgcolor="#0a0a0a" style="background:#0a0a0a;border-top:3px solid #d8ff3a;padding:28px 32px 30px;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif;color:#f4efe6;">\n    <div style="font-family:Impact,\'Arial Black\',\'Helvetica Inserat\',sans-serif;font-size:20px;line-height:22px;letter-spacing:.02em;text-transform:uppercase;color:#f4efe6;font-weight:900;margin-bottom:14px;">{nazwa_warsztatu}</div>\n    <div style="font-size:15px;line-height:22px;color:#f4efe6;font-weight:600;margin-bottom:6px;">{adres_warsztatu}</div>\n    <div style="font-size:15px;line-height:22px;color:#f4efe6;margin-bottom:6px;">tel. <a href="tel:+48514296809" style="color:#d8ff3a;text-decoration:none;font-weight:700;">{telefon_warsztatu}</a></div>\n    <div style="font-size:13px;line-height:20px;color:#b8b3a5;margin-bottom:18px;">{godziny_otwarcia}</div>\n    <table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr><td style="background:#d8ff3a;padding:0;">\n      <a href="{mapy_url}" target="_blank" rel="noopener" style="display:inline-block;background:#d8ff3a;color:#0a0a0a;text-decoration:none;font-family:Impact,\'Arial Black\',\'Helvetica Inserat\',sans-serif;font-size:15px;line-height:15px;letter-spacing:.14em;text-transform:uppercase;padding:14px 24px;font-weight:900;">&#x2192; Mapa dojazdu</a>\n    </td></tr></table>\n    <div style="margin-top:20px;font-size:11px;line-height:16px;color:#8a8780;opacity:.85;">Odpisz STOP, jeśli nie chcesz dostawać powiadomień o swoich zleceniach.</div>\n  </td></tr>'
)
WHERE name = 'Gotowe do odbioru (EMAIL)'
  AND body_html IS NOT NULL
  AND body_html NOT LIKE '%background:#0a0a0a;border-top:3px solid #d8ff3a;%';

-- ─── 3. Prosba o opinie (EMAIL) ─────────────────────────────────────────────────────────────
UPDATE message_template
SET body_html = REPLACE(
    body_html,
    E'  <!-- FOOTER -->\n  <tr><td class="footer-bg ink-text" style="background:#ebe4d4;border-top:2px solid #0a0a0a;padding:28px 32px 30px;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif;color:#0a0a0a;">\n    <div style="font-family:Impact,\'Arial Black\',\'Helvetica Inserat\',sans-serif;font-size:20px;line-height:22px;letter-spacing:.02em;text-transform:uppercase;color:#0a0a0a;font-weight:900;margin-bottom:14px;">{nazwa_warsztatu}</div>\n    <div style="font-size:15px;line-height:22px;color:#0a0a0a;font-weight:600;margin-bottom:6px;">{adres_warsztatu}</div>\n    <div style="font-size:15px;line-height:22px;color:#0a0a0a;margin-bottom:6px;">tel. <a href="tel:+48514296809" style="color:#0a0a0a;text-decoration:none;font-weight:700;">{telefon_warsztatu}</a></div>\n    <div style="font-size:13px;line-height:20px;color:#3a3833;margin-bottom:18px;">{godziny_otwarcia}</div>\n    <table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr><td style="background:#d8ff3a;padding:0;">\n      <a href="{mapy_url}" target="_blank" rel="noopener" style="display:inline-block;background:#d8ff3a;color:#0a0a0a;text-decoration:none;font-family:Impact,\'Arial Black\',\'Helvetica Inserat\',sans-serif;font-size:15px;line-height:15px;letter-spacing:.14em;text-transform:uppercase;padding:14px 24px;font-weight:900;">&#x2192; Mapa dojazdu</a>\n    </td></tr></table>\n    <div style="margin-top:20px;font-size:11px;line-height:16px;color:#6b6960;opacity:.85;">Odpisz STOP, jeśli nie chcesz dostawać powiadomień o swoich zleceniach.</div>\n  </td></tr>',
    E'  <!-- FOOTER v3 (always-dark; resists dark-mode CSS inversion) -->\n  <tr><td class="footer-bg" bgcolor="#0a0a0a" style="background:#0a0a0a;border-top:3px solid #d8ff3a;padding:28px 32px 30px;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif;color:#f4efe6;">\n    <div style="font-family:Impact,\'Arial Black\',\'Helvetica Inserat\',sans-serif;font-size:20px;line-height:22px;letter-spacing:.02em;text-transform:uppercase;color:#f4efe6;font-weight:900;margin-bottom:14px;">{nazwa_warsztatu}</div>\n    <div style="font-size:15px;line-height:22px;color:#f4efe6;font-weight:600;margin-bottom:6px;">{adres_warsztatu}</div>\n    <div style="font-size:15px;line-height:22px;color:#f4efe6;margin-bottom:6px;">tel. <a href="tel:+48514296809" style="color:#d8ff3a;text-decoration:none;font-weight:700;">{telefon_warsztatu}</a></div>\n    <div style="font-size:13px;line-height:20px;color:#b8b3a5;margin-bottom:18px;">{godziny_otwarcia}</div>\n    <table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr><td style="background:#d8ff3a;padding:0;">\n      <a href="{mapy_url}" target="_blank" rel="noopener" style="display:inline-block;background:#d8ff3a;color:#0a0a0a;text-decoration:none;font-family:Impact,\'Arial Black\',\'Helvetica Inserat\',sans-serif;font-size:15px;line-height:15px;letter-spacing:.14em;text-transform:uppercase;padding:14px 24px;font-weight:900;">&#x2192; Mapa dojazdu</a>\n    </td></tr></table>\n    <div style="margin-top:20px;font-size:11px;line-height:16px;color:#8a8780;opacity:.85;">Odpisz STOP, jeśli nie chcesz dostawać powiadomień o swoich zleceniach.</div>\n  </td></tr>'
)
WHERE name = 'Prosba o opinie (EMAIL)'
  AND body_html IS NOT NULL
  AND body_html NOT LIKE '%background:#0a0a0a;border-top:3px solid #d8ff3a;%';

-- ─── 4. Dr Shoes - followup (EMAIL) ─────────────────────────────────────────────────────────
-- V031 embedded the same V031 footer block inside the body_html, so the same
-- REPLACE swaps it cleanly.
UPDATE message_template
SET body_html = REPLACE(
    body_html,
    E'  <!-- FOOTER -->\n  <tr><td class="footer-bg ink-text" style="background:#ebe4d4;border-top:2px solid #0a0a0a;padding:28px 32px 30px;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif;color:#0a0a0a;">\n    <div style="font-family:Impact,\'Arial Black\',\'Helvetica Inserat\',sans-serif;font-size:20px;line-height:22px;letter-spacing:.02em;text-transform:uppercase;color:#0a0a0a;font-weight:900;margin-bottom:14px;">{nazwa_warsztatu}</div>\n    <div style="font-size:15px;line-height:22px;color:#0a0a0a;font-weight:600;margin-bottom:6px;">{adres_warsztatu}</div>\n    <div style="font-size:15px;line-height:22px;color:#0a0a0a;margin-bottom:6px;">tel. <a href="tel:+48514296809" style="color:#0a0a0a;text-decoration:none;font-weight:700;">{telefon_warsztatu}</a></div>\n    <div style="font-size:13px;line-height:20px;color:#3a3833;margin-bottom:18px;">{godziny_otwarcia}</div>\n    <table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr><td style="background:#d8ff3a;padding:0;">\n      <a href="{mapy_url}" target="_blank" rel="noopener" style="display:inline-block;background:#d8ff3a;color:#0a0a0a;text-decoration:none;font-family:Impact,\'Arial Black\',\'Helvetica Inserat\',sans-serif;font-size:15px;line-height:15px;letter-spacing:.14em;text-transform:uppercase;padding:14px 24px;font-weight:900;">&#x2192; Mapa dojazdu</a>\n    </td></tr></table>\n    <div style="margin-top:20px;font-size:11px;line-height:16px;color:#6b6960;opacity:.85;">Odpisz STOP, jeśli nie chcesz dostawać powiadomień o swoich zleceniach.</div>\n  </td></tr>',
    E'  <!-- FOOTER v3 (always-dark; resists dark-mode CSS inversion) -->\n  <tr><td class="footer-bg" bgcolor="#0a0a0a" style="background:#0a0a0a;border-top:3px solid #d8ff3a;padding:28px 32px 30px;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif;color:#f4efe6;">\n    <div style="font-family:Impact,\'Arial Black\',\'Helvetica Inserat\',sans-serif;font-size:20px;line-height:22px;letter-spacing:.02em;text-transform:uppercase;color:#f4efe6;font-weight:900;margin-bottom:14px;">{nazwa_warsztatu}</div>\n    <div style="font-size:15px;line-height:22px;color:#f4efe6;font-weight:600;margin-bottom:6px;">{adres_warsztatu}</div>\n    <div style="font-size:15px;line-height:22px;color:#f4efe6;margin-bottom:6px;">tel. <a href="tel:+48514296809" style="color:#d8ff3a;text-decoration:none;font-weight:700;">{telefon_warsztatu}</a></div>\n    <div style="font-size:13px;line-height:20px;color:#b8b3a5;margin-bottom:18px;">{godziny_otwarcia}</div>\n    <table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr><td style="background:#d8ff3a;padding:0;">\n      <a href="{mapy_url}" target="_blank" rel="noopener" style="display:inline-block;background:#d8ff3a;color:#0a0a0a;text-decoration:none;font-family:Impact,\'Arial Black\',\'Helvetica Inserat\',sans-serif;font-size:15px;line-height:15px;letter-spacing:.14em;text-transform:uppercase;padding:14px 24px;font-weight:900;">&#x2192; Mapa dojazdu</a>\n    </td></tr></table>\n    <div style="margin-top:20px;font-size:11px;line-height:16px;color:#8a8780;opacity:.85;">Odpisz STOP, jeśli nie chcesz dostawać powiadomień o swoich zleceniach.</div>\n  </td></tr>'
)
WHERE name = 'Dr Shoes - followup (EMAIL)'
  AND body_html IS NOT NULL
  AND body_html NOT LIKE '%background:#0a0a0a;border-top:3px solid #d8ff3a;%';
